# 矩陣理論（Matrix Theory）

![Creative Commons License](https://i.creativecommons.org/l/by/4.0/88x31.png)

This work by Jephian Lin is licensed under a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/).

_Tested on SageMath version 8.7_

## 反矩陣

在數字的世界裡  
任何數乘上 $1$ 數字都不變

在矩陣世界裡也有一個類似 $1$ 的角色  
叫作**單位矩陣** $I = 
\begin{bmatrix}
 1 & 0 & \cdots & 0 \\
 0 & 1 & \ddots & \vdots \\
 \vdots & \ddots & \ddots & 0 \\
 0 & \cdots & 0 & 1
\end{bmatrix}$

任何矩陣乘上單位矩陣乘都不會改變

In [2]:
A = matrix([
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ])
I = identity_matrix(3)
print("A =")
print(A)
print("AI =")
print(A * I)
print("IA =")
print(I * A)

A =
[1 2 3]
[4 5 6]
[7 8 9]
AI =
[1 2 3]
[4 5 6]
[7 8 9]
IA =
[1 2 3]
[4 5 6]
[7 8 9]


數字世界裡的任何非零數 $x$  
都有一個**倒數** $x^{-1}$  
使得 $x\cdot x^{-1} = 1$

矩陣世界裡的部份的方陣 $A$（長寬一樣的矩陣）  
也有一個**反矩陣** $A^{-1}$  
使得 $A\cdot A^{-1} = I$

In [4]:
A = matrix([
        [1,2],
        [3,4]
    ])
Ainv = A.inverse()
print("A =")
print(A)
print("Ainv =")
print(Ainv)
print("A Ainv =")
print(A * Ainv)

A =
[1 2]
[3 4]
Ainv =
[  -2    1]
[ 3/2 -1/2]
A Ainv =
[1 0]
[0 1]


### 用反矩陣求解
若一個線性方程組所對應的矩陣有反矩陣  
則方程組的解可以用反矩陣寫出來  
$\begin{aligned}
 x + 2y &= 3 \\
3x + 4y &= 7
\end{aligned}\implies  
\begin{bmatrix}
 1 & 2 \\ 
 3 & 4 
\end{bmatrix}
\begin{bmatrix} x \\ y \end{bmatrix} 
=
\begin{bmatrix} 3 \\ 7 \end{bmatrix}$  
$\implies\begin{bmatrix} x \\ y \end{bmatrix} = 
\begin{bmatrix}  
 1 & 2 \\
 3 & 4 
\end{bmatrix}^{-1}
\begin{bmatrix} 3 \\ 7 \end{bmatrix}$

In [6]:
A = matrix([
        [1,2],
        [3,4]
    ])
b = matrix([
        [3],
        [7]
    ])
Ainv = A.inverse()
print("Ainv =")
print(Ainv)
print("b =")
print(b)
print("Ainv b =")
print(Ainv * b)

Ainv =
[  -2    1]
[ 3/2 -1/2]
b =
[3]
[7]
Ainv b =
[1]
[1]


### 如何求反矩陣
令 ${\bf e}_1 = (1,0,0,\ldots,0)^\top$,  
${\bf e}_2 = (0,1,0,\ldots,0)^\top$, $\ldots$  
方程式 $A{\bf v} = {\bf e}_j$ 中 ${\bf v}$ 的解就是 $A^{-1}$ 的第 $j$ 行

$\begin{bmatrix}
 1 & 2 \\
 3 & 4 
\end{bmatrix}
\begin{bmatrix} x \\ y \end{bmatrix}
=
\begin{bmatrix} 1 \\ 0 \end{bmatrix}  
\implies 
\begin{bmatrix} x \\ y \end{bmatrix}
=
\begin{bmatrix} -2 \\ 3/2 \end{bmatrix}$  
$\begin{bmatrix}
 1 & 2 \\
 3 & 4 
\end{bmatrix}
\begin{bmatrix} x \\ y \end{bmatrix}
=
\begin{bmatrix} 0 \\ 1 \end{bmatrix}  
\implies 
\begin{bmatrix} x \\ y \end{bmatrix}
=
\begin{bmatrix} 3/2 \\ -1/2 \end{bmatrix}$

$\begin{bmatrix}
 1 & 2 \\
 3 & 4 
\end{bmatrix}^{-1}
= 
\begin{bmatrix}
 -2 & 3/2 \\
 3/2 & -1/2
\end{bmatrix}$

## 行列式值
每個方陣可以計算其行列式值  
行列式值可以用來  
判斷一個方陣是否有反矩陣

$2\times 2$ 方陣的行列式值為  
$\det\begin{bmatrix} 
 a & b \\
 c & d 
\end{bmatrix}
= ad - bc$

In [7]:
A = matrix([
        [1,2],
        [3,4]
    ])
A.determinant()

-2

$3\times 3$ 方陣的行列式值為  
$\det\begin{bmatrix} 
 a & b & c \\
 d & e & f \\
 g & h & i
\end{bmatrix}
= aei + bfg + cdh - ceg - bdi - afh$

In [8]:
A = matrix([
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ])
A.determinant()

0

高階矩陣必須利用**降階**的方式  
來計算行列式值  

若 $A=\begin{bmatrix}a_{ij}\end{bmatrix}$ 為一 $n\times n$ 矩陣  
令 $A_j$ 為一 $(n-1)\times(n-1)$ 矩陣  
這個小矩陣是由 $A$ 將第 $0$ 列及第 $j$ 行刪掉得來  
則 $\det(A) = \sum_{j=0}^{n-1} (-1)^{0+j}a_{0j}\det(A_j)$

In [25]:
A = matrix([
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ])
A0 = A[[1,2],[1,2]]
A1 = A[[1,2],[0,2]]
A2 = A[[1,2],[0,1]]
print("A1 =")
print(A0)
print("det(A0) = %s"%A0.determinant())
print("A2 =")
print(A1)
print("det(A1) = %s"%A1.determinant())
print("A3 =")
print(A2)
print("det(A2) = %s"%A2.determinant())

A1 =
[5 6]
[8 9]
det(A0) = -3
A2 =
[4 6]
[7 9]
det(A1) = -6
A3 =
[4 5]
[7 8]
det(A2) = -3


若 `A` 為 Sage 裡的一方陣  
則 `A.determinant()` 會自動計算行列式值

In [33]:
A = matrix([
        [0, 1, 0, 1],
        [1, 0, 1, 0],
        [0, 1, 0, 1],
        [1, 0, 1, 0]
    ])
A.determinant()

0

就算式子裡有變數也可以算出來

In [34]:
x = var('x')
Ax = matrix([
        [x, -1, 0, -1],
        [-1, x, -1, 0],
        [0, -1, x, -1],
        [-1, 0, -1, x]
    ])
Ax.determinant()

x^4 - 4*x^2

## 特徵多項式
一個方陣的**特徵多項式**  
定義為 $p_A(x) = \det(xI-A)$

In [35]:
x = var('x')
A = matrix([
        [0, 1, 0, 1],
        [1, 0, 1, 0],
        [0, 1, 0, 1],
        [1, 0, 1, 0]
    ])
Ax = x*identity_matrix(4) - A
p = Ax.determinant()
print("xI - A =")
print(Ax)
print("p_A(x) = %s"%p)

xI - A =
[ x -1  0 -1]
[-1  x -1  0]
[ 0 -1  x -1]
[-1  0 -1  x]
p_A(x) = x^4 - 4*x^2


一個 $n\times n$ 的矩陣 $A$  
其特徵多項式 $p_A(x)$ 是一個 $n$ 階的多項式  
因此有 $p_A(x)=0$ 有 $n$ 個解  
（有可能為複數解）  
這些解叫作 $A$ 的**特徵值**

In [37]:
factor(p) # x = 0, 0, 2, -2

(x + 2)*(x - 2)*x^2

當 $x$ 為 $A$ 的特徵值時  
$xI - A$ 的行列式值為零  
而 $(xI - A){\bf v} = {\bf 0}$ 找得到非零的解 ${\bf v}$  
這個 ${\bf v}$ 叫作 $A$ 的特徵向量  

#### Case 1. $x=2$

In [54]:
A = matrix([
        [0, 1, 0, 1],
        [1, 0, 1, 0],
        [0, 1, 0, 1],
        [1, 0, 1, 0]
    ])
Ax2 = 2*identity_matrix(4) - A
print(Ax2)

[ 2 -1  0 -1]
[-1  2 -1  0]
[ 0 -1  2 -1]
[-1  0 -1  2]


In [55]:
ker = Ax2.right_kernel()
ker

Free module of degree 4 and rank 1 over Integer Ring
Echelon basis matrix:
[1 1 1 1]

$(2I - A){\bf v} = {\bf 0}$

In [56]:
v2 = ker.basis()[0]
Ax2 * v2

(0, 0, 0, 0)

$A{\bf v} = 2{\bf v}$

In [57]:
A * v2

(2, 2, 2, 2)

#### Case 2. $x=0$

若一個解有重根  
則解出來的 ${\bf v}$ 也有可能很多個

In [58]:
A = matrix([
        [0, 1, 0, 1],
        [1, 0, 1, 0],
        [0, 1, 0, 1],
        [1, 0, 1, 0]
    ])
Ax0 = 0*identity_matrix(4) - A
print(Ax0)

[ 0 -1  0 -1]
[-1  0 -1  0]
[ 0 -1  0 -1]
[-1  0 -1  0]


In [62]:
ker = Ax0.right_kernel()
ker

Free module of degree 4 and rank 2 over Integer Ring
Echelon basis matrix:
[ 1  0 -1  0]
[ 0  1  0 -1]

In [64]:
v0,u0 = ker.basis()

#### Case 3. $x=-2$

同樣的，我們也可以計算 $x=-2$  
對應到的特徵向量  

In [67]:
A = matrix([
        [0, 1, 0, 1],
        [1, 0, 1, 0],
        [0, 1, 0, 1],
        [1, 0, 1, 0]
    ])
Axm2 = (-2)*identity_matrix(4) - A
ker = Axm2.right_kernel()
vm2 = ker.basis()[0]
vm2

(1, -1, 1, -1)

## 對角化
如果運氣好  
矩陣 $A$ 有找到 $n$ 個*獨立*的特徵向量  
${\bf v}_0, \ldots, {\bf v}_{n-1}$  
其對應到的特徵值為  
$\lambda_0, \ldots, \lambda_{n-1}$  
則我們有  
$A\begin{bmatrix}
 | & \cdots & | \\
 {\bf v}_0 & \cdots & {\bf v}_{n-1} \\
 | & \cdots & | \\
\end{bmatrix}
=
\begin{bmatrix}
 | & \cdots & | \\
 \lambda_0{\bf v}_0 & \cdots & \lambda_{n-1}{\bf v}_{n-1} \\
 | & \cdots & | \\
\end{bmatrix}
=
\begin{bmatrix}
 | & \cdots & | \\
 {\bf v}_0 & \cdots & {\bf v}_{n-1} \\
 | & \cdots & | \\
\end{bmatrix}
\begin{bmatrix}
 \lambda_0 & ~ & 0 \\
 ~ & \ddots & ~ \\
 0 & ~ & \lambda_{n-1}
\end{bmatrix}$

改寫成 $AV = VD$  
如此一來就有 $V^{-1}AV = D$  
而這個過程叫作 $A$ 的**對角化**

以剛剛的例子來說  
四個向量都已經算好了  

In [84]:
print(v2) # lambda = 2
print(v0) # lambda = 0
print(u0) # lambda = 0
print(vm2) # lambda = -2

(1, 1, 1, 1)
(1, 0, -1, 0)
(0, 1, 0, -1)
(1, -1, 1, -1)


In [70]:
V = matrix([v2, v0, u0, vm2]).transpose()
V

[ 1  1  0  1]
[ 1  0  1 -1]
[ 1 -1  0  1]
[ 1  0 -1 -1]

In [72]:
A * V

[ 2  0  0 -2]
[ 2  0  0  2]
[ 2  0  0 -2]
[ 2  0  0  2]

In [74]:
D = matrix([
        [2, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, -2]
    ])
V * D

[ 2  0  0 -2]
[ 2  0  0  2]
[ 2  0  0 -2]
[ 2  0  0  2]

In [75]:
V.inverse() * A * V

[ 2  0  0  0]
[ 0  0  0  0]
[ 0  0  0  0]
[ 0  0  0 -2]

特徵值和特徵向量的計算  
通常非常煩雜  

若 `A` 為 Sage 裡的矩陣  
則 `A.eigenmatrix_right()`  
可以把 $D$ 和 $V$ 算出來  
（其中 $V$ 的列排序不見得和我們算得一樣  
有和 $D$ 相對應就可以）

In [76]:
A.eigenmatrix_right()

(
[ 2  0  0  0]  [ 1  1  1  0]
[ 0 -2  0  0]  [ 1 -1  0  1]
[ 0  0  0  0]  [ 1  1 -1  0]
[ 0  0  0  0], [ 1 -1  0 -1]
)

大型的矩陣幾乎不可能  
用代數運算來找到  
確切的特徵值和特徵向量  
但可以用數值方法來求得近似值  
（一直到現在  
如何有效的計算特徵值和特徵向量  
都還是很重要的研究領域）

這種數值解可以利用
SciPy 套件裡的 linalg 模組計算  
```Python
import scipy.linalg as LA
LA.eig(A) # 適用任何方陣
LA.eigh(A) # 適用對稱矩陣
```

In [79]:
import numpy as np
import scipy.linalg as LA

In [82]:
npA = np.array(A)
LA.eigh(A)

(array([ -2.00000000e+00,   0.00000000e+00,   2.66453526e-15,
          2.00000000e+00]),
 array([[  5.00000000e-01,   0.00000000e+00,   7.07106781e-01,
           5.00000000e-01],
        [ -5.00000000e-01,  -7.07106781e-01,   3.92523115e-16,
           5.00000000e-01],
        [  5.00000000e-01,   0.00000000e+00,  -7.07106781e-01,
           5.00000000e-01],
        [ -5.00000000e-01,   7.07106781e-01,   3.92523115e-16,
           5.00000000e-01]]))

## 動手試試看

##### 練習 1

已知一組聯立方程式：  
$3X + Y = 16$  
$2X + 2Y = 20$  
請將該方程組寫成對應的矩陣，並用反矩陣的方法求該方程組的解。

In [1]:
### your answer here

##### 練習 2

已知一組聯立方程式：  
$2X + Y + 2Z = 25$  
$X + Y + 4Z = 23$  
$2Y + Z = 20$  
請將該方程組寫成對應的矩陣，並用反矩陣的方法求該方程組的解。

In [2]:
### your answer here

##### 練習 3

定義一個函數，其功能為：  
傳入`3個`在__三維空間__中的線性獨立向量，  
並回傳3個向量所張出來的**六面體體積**。

In [3]:
### your answer here

##### 練習 4

已知一矩陣；
$A = 
\begin{bmatrix} 
\frac{1}{2} & \frac{\sqrt{3}}{2} \\
\frac{-\sqrt{3}}{2} & \frac{1}{2}
\end{bmatrix}$  

請試著找反矩陣 $A^{-1}$  
並觀察 $A^{-1}$ 和 $A^\top$ 的關係。

In [ ]:
### your answer here

##### 練習 5

已知一矩陣：  

$A = 
\begin{bmatrix} 
 1 & 2 & 3 \\
 0 & 2 & 3 \\
 0 & 0 & 0
\end{bmatrix}$  
請用上面提到的方法將矩陣 `A` 對角化。  
(找出$A = VDV^{-1}$)

In [4]:
### your answer here

##### 練習 6

承上題，運用對角化出來的結果，計算出 `矩陣A` 的 `10` 次方。  
($A^{10} = VDV^{-1}\cdot VDV^{-1}\cdot\cdots\cdot VDV^{-1}$)

In [5]:
### your answer here

##### 練習 7

已知每年會有 10% 的人從 A 市遷移至 B 市，  
且有 20% 的人從 B 市遷移至 A 市，因此我們有轉移矩陣：  
$A = \begin{bmatrix} 
0.9 & 0.2 \\
0.1 & 0.8 
\end{bmatrix}$    
請將矩陣 A 對角化，並觀察 $A^{n}$ 當 $n$ 趨向無限時，  
A 市和 B 市的人口最終會呈現什麼比例？

In [6]:
### your answer here

##### 練習 8

線性代數中，有一個定理叫做_凱萊–哈密頓定理（Cayley–Hamilton theorem）_，其內容大致上是說：  
如果我們有一個`n階方陣` $A$ ，我們定義一條多項式 $p(\lambda)$ 為 $\lambda I_n - A$ 的絕對值。  
（也就是 $p(\lambda) = \det(\lambda I_n - A)$）  
則如果我們把 $p(\lambda)$ 帶入 $A$ 進去的話，結果會是 $O_n$  
例如：$A = \begin{bmatrix} 1& 3 \\ -1& -2 \end{bmatrix}$ ，
則 $p(\lambda) = \det\begin{bmatrix} \lambda-1& -3 \\ -(-1)& \lambda-(-2) \end{bmatrix} = \lambda^2 + \lambda + 1$  
將 $\lambda$ 代入 $A$ 的話：$A^2 + A + I_2 = 
\begin{bmatrix} -2& -3 \\ 1& 1 \end{bmatrix} + 
\begin{bmatrix} 1& 3 \\ -1& -2 \end{bmatrix} + 
\begin{bmatrix} 1& 0 \\ 0& 1 \end{bmatrix} = 
\begin{bmatrix} 0& 0 \\ 0& 0 \end{bmatrix}$  
  
---
  
就以上定理，已知一矩陣 $A = \begin{bmatrix} 1& 2 \\ 3& 4 \end{bmatrix}$，請計算出它的 $p(\lambda)$  
並驗證 $p(A)$ 是否為 $O_2$

In [ ]:
### your answer here

##### 練習 9

已知一矩陣：  
$A = 
\begin{bmatrix} 
 4 & 3 \\
 -7 & -5 
\end{bmatrix}$   
請利用 _凱萊–哈密頓定理_ ，求出 $A^6$   
（提示：$(x - 1)(x^2 + x + 1) = x^3 - 1$）

In [ ]:
### your answer here

##### 練習 10

線性代數中若一個方形矩陣，以對角線為軸左右對稱的話，則稱之為對稱矩陣  
例如：$A = 
\begin{bmatrix}
1 & 2 & 3 \\
2 & 1 & 2 \\
3 & 2 & 1 
\end{bmatrix}$  
同時 $A = A^\top$ ，而且當 $A$ 中的元素都是實數時 $A$ 必可對角化。  

請試著對角化 $A$

In [ ]:
### your answer here